### ISSUE TITLE
Google Drive Folder not working

### ISSUE THREAD

**Issue by tuecke** [globusonline/google-drive-registration-app#12]
If I try to enter a Google Drive Folder I always get:

"Share creation failed: Invalid host_path"

I've tried:
/My Drive/
/My Drive
My Drive
/Starred
/Starred/

**Comment by jaswilli** [comment]
I think this is a GCS Manager bug. I'll take care of it.

**Comment by jaswilli** [comment]
@tuecke I fixed-up the way the GCS Manager turns around and creates the shared endpoint with Transfer so now it doesn't error out. After doing that we discovered that it doesn't appear that gridftp is actually paying attention to the `path` value that gets stored in the `collection` table.

I pinged Mike and Joe about it in the slack channel.

**Comment by jaswilli** [comment]
Mike fixed the gridftp issue and now it looks like it's working as expected.
