### ISSUE TITLE
Change identity page

### ISSUE THREAD

**Issue by tuecke** [globusonline/google-drive-registration-app#17]
When the user clicks the identity "change" link on the Google Account registration page, it should go to a page that has the following:

Header: Change Globus identity for Google Account registration
A Google Account registration on a Globus Connect Server is tied to one of your Globus Account's linked identities. You can only use, update, or delete a Google Account registration if you are logged into a Globus account with this identity linked to it.

Header: Select a Globus identity
Select the Globus identity to which you want to tie your Google Account registration on this Globus Connect Server:

tuecke@globusid.org
sjt@globusid.org
tuecke@uchicago.edu

--------------- or -----------------

Header: Link a new Globus identity

Link a new Globus identity to your Globus Account, and use it for your Google Account registration on this Globus Connect Server.

(If server has a policy that restricts identity providers)
This Globus Connect Server, gcs-dev.globuscs.info, only allows Google Account registrations to be tied to Globus identities from the following identity providers. Select the provider from which you want to link an identity to your Globus Account:

> Globus ID
> University of Chicago

(If server allows any identity provider)
Select the provider from which you want to link an identity to your Globus Account, and press Continue.
[Identity provider input box, like Globus Auth]
Button: [Continue]

**Comment by corpulentcoffee** [comment]
Per discussion at end of #16, the "change identity" / "link identity" option on the Google account registration step should unconditionally be "change identity" and should link to this new page described here.

**Comment by tuecke** [comment]
Per today's discussion, forget my changes above.  Take 2...

On the /register page, get rid of "This Google Account will be registered on this Globus Connect Server with your tuecke@globusid.org identity. [change identity]". Instead, always have it show something similar to the current "change identity" behavior with multiple identities:

---
Which Globus identity do you want to register this Google Account with on this Globus Connect Server? In the future, you will only be able to use, update, or delete this Google Account registration if you are logged into a Globus account with this identity linked to it.

Globus Identity: [select identity dropdown]
or link another Globus identity

---
Pre-select the identity in the dropdown, just like we are currently pre-selecting the identity in the sentence. 

When "or link another Globus identity" is clicked, go do the /link page, but with these changes to that page:

---
Header: Link a new Globus identity

Link a new Globus identity to your Globus Account, so that you can use it for your Google Account registration on this Globus Connect Server.

(If server has a policy that restricts identity providers)
This Globus Connect Server, gcs-dev.globuscs.info, only allows Google Account registrations to be tied to Globus identities from the following identity providers. To continue, select the identity provider from which you want to link an identity to your Globus Account:

Globus ID
University of Chicago

Otherwise, return to registering a Google account without linking a new Globus identity.  // link back to /register

(If server allows any identity provider)
Select the identity provider from which you want to link an identity to your Globus Account, and press Continue:
[Identity provider input box, like Globus Auth]
Button: [Continue]

Otherwise, return to registering a Google account without linking a new Globus identity.  // link back to /register

**Comment by vytas** [comment]
Is there a reason we are taking users to a new page? Can this not be done inline as illustrated (just click on **change identity**) in the [wireframes](http://globusonline.github.io/UX/projects/2017_02-google_drive_connection/prototype/#g=1&p=no_google_account_registered_v1)?

**Comment by corpulentcoffee** [comment]
I have completed the changes required to switch from the "inline change-identity" wireframe flow to the https://github.com/globusonline/google-drive-registration-app/issues/17#issuecomment-282429061 flow in a [new branch](https://github.com/globusonline/google-drive-registration-app/compare/master...corpulentcoffee:issue-17) **except** for the following request:

> (If server allows any identity provider) [...]
> [Identity provider input box, like Globus Auth]

This part requires a find-all identity-provider call to implement a dropdown similar to Globus Auth. Although this is available via the `/p/identity_providers` API, it's contentious and may not make it to the finalized version of the API.

Is linking to Globus Auth and allowing Globus Auth to render the identity provider dropdown itself a suitable alternative so we can avoid the find-all call?

![image](https://cloud.githubusercontent.com/assets/3958448/23385924/e645da6e-fd18-11e6-8e8e-27c35e0323a4.png)

![image](https://cloud.githubusercontent.com/assets/3958448/23385934/f5f87aa2-fd18-11e6-86d5-5fe2880e5db2.png)

**Comment by tuecke** [comment]
Yes, this flow is fine.  I forgot we weren't doing inline search for all identity providers, and just going to the auth link page to do the selection there.
