### ISSUE TITLE
Clean up horizontal rules with words on them

### ISSUE THREAD

**Issue by corpulentcoffee** [globusonline/google-drive-registration-app#19]
In #16, @tuecke asked for a horizontal rule with an "or" in the middle of it.
0011485705b5 implements this in a hacky way.

@teresas, can you see if there is a better Bootstrap-y way to do this?

**Comment by teresas** [comment]
There really isn't a bootstrap-y way to do this, but I moved the styling to a class in the css file so it's not inline. Changes should be on branch i19

**Comment by corpulentcoffee** [comment]
Works for me. Thanks!
