### ISSUE TITLE
Improve account menu appearance and clean up unneeded/unused CSS

### ISSUE THREAD

**Issue by corpulentcoffee** [globusonline/google-drive-registration-app#20]
#9 from @tuecke re-introduces the account menu in the registration app.

![image](https://cloud.githubusercontent.com/assets/3958448/23277189/9e0e3302-f9d2-11e6-83d5-27efa46626b7.png)

I vaguely used the HTML from https://github.com/globusonline/google-drive-registration-app/tree/5b4e4260650f9e1bb021e2537b32c197c8b24607/app/styles for the account button itself before it was removed in a later revision, but I didn't have HTML/styling for the dropdown itself.

@teresas, can you grab the latest `master` and

- [x] take a quick pass at improving the appearance of the dropdown (e.g. fixing the hover effect when the Logout link is moused over)
- [x] remove any CSS styles from `app.css` related to the menu that we won't need (maybe `.navbar-toggler` and/or `#navbar-nav`, depending on if you reintroduce those when you improve the menu's appearance)

The markup for the toggle button and the menu itself is in [app/pods/components/account-menu/template.hbs](/globusonline/google-drive-registration-app/blob/master/app/pods/components/account-menu/template.hbs). If you want to change the classes on the wrapper around those two, you can do so by changing the `classNames` in [app/pods/components/account-menu/component.js](/globusonline/google-drive-registration-app/blob/master/app/pods/components/account-menu/component.js).

**Comment by teresas** [comment]
@corpulentcoffee I just pushed changes on the i20 branch. Take a look and let me know if it needs adjustments.

**Comment by corpulentcoffee** [comment]
Thanks!
