### ISSUE TITLE
SVG bullets on /link do not render on Firefox

### ISSUE THREAD

**Issue by corpulentcoffee** [globusonline/google-drive-registration-app#22]
Per @ranantha 
![image](https://cloud.githubusercontent.com/assets/3958448/23313609/04214682-fa84-11e6-897d-6b717f2890b7.png)

Probably the same issue as Edge/IE.

**Comment by teresas** [comment]
@corpulentcoffee Yeah, it looks like the same issue as Edge/IE. I'm going to change the way it pulls the background image by doing it the old fashioned way (an image of the right color for the regular and a separate with right color for rollover state)

**Comment by corpulentcoffee** [comment]
Closed by #24
