### ISSUE TITLE
Loading spinner

### ISSUE THREAD

**Issue by tuecke** [globusonline/google-drive-registration-app#25]
I think the loading page has too much text, and nothing that's what I would expect of a loading spinner.  Every time I hit the loading page, I feel like I need to read it.  We should simplify the text, and add a clear spinner on the page.

**Comment by corpulentcoffee** [comment]
Hey @teresas (and maybe @vytas), can you look at doing a loading screen for this application?

If it includes any text, it should be generic enough to cover the different things the application might need to do to get enough information to render the page (e.g. looking up the user's identity set, searching for the host endpoint, looking up policies, looking up identity provider information, looking up available credentials). Technically the loading screen also displays during token invalidation in the `/logout` route, but that could be changed.

With the development server running, you can visit https://localhost:4200/loading to get at the loading screen. Its template is at `app/pods/loading/template.hbs`.

You can pull in any of your spritesheet SVGs with `{{svg-icon name='xxx'}}` where `'xxx'` is the symbol ID from `public/assets/images/icons/icons.svg` (like the `'cloud-download'` that is already there).

If you need to introduce a whole new physical SVG (e.g. for animation), you can also drop that in `public/assets/images/` wherever you want and then include it using a regular `<img src='/assets/images/xxx' alt="Loading...">`-type tag.
