### ISSUE TITLE
Credential management route

### ISSUE THREAD

**Issue by corpulentcoffee** [globusonline/google-drive-registration-app#32]
Today, we will be able:
- list the credentials
- "refresh" a credential (by doing a more explicit version of the "re-adding a Google username that is already in the GCS database refreshes it" behavior we have today)

Things we cannot do at this stage:
- cannot delete credentials
- cannot be told by the API that a credential is bad

cc @ranantha

**Comment by corpulentcoffee** [comment]
Update 3/27:

- credentials will have a `deleted` and `invalid` column
  - `deleted` is when the user "deletes" the credential (soft delete)
  - `invalid` is when GCS has gotten back a 401 when trying to exchange a refresh token for an access token
- a user that goes through the same identity ID + Google username + sub ID will get that credential's flags reset to `deleted=False` and `invalid=False`

**Comment by jaswilli** [comment]
Here's an example `GET /user_credentials` response from the updated API:

```
[
  {
    "display_name": "jaswilli@globus.org", 
    "id": "1bcef836-ebd8-4e97-9066-c32f603ac2a8", 
    "identity_id": "3adfb126-cc28-11e5-8f8a-7b8903eaee67", 
    "invalid": false, 
    "storage_credential": null, 
    "storage_type": "Google Drive", 
    "storage_type_id": "976cf0cf-78c3-4aab-82d2-7c16adbcc281"
  }
]
```

**Comment by corpulentcoffee** [comment]
This is supported now.
