### ISSUE TITLE
GCS manager scope consent text

### ISSUE THREAD

**Issue by tuecke** [globusonline/google-drive-registration-app#7]
The consent page currently says "Globus Connect Server gcs-dev.globuscs.info".  Change to "Manage collections on Globus Connect Server gcs-dev.globuscs.info".

Then in the detailed description, change "Manage collections on gcs-dev.globuscs.info" to, "Full control over creating, managing, and deleting your collections and your storage system credentials on Globus Connect Server gcs-dev.globuscs.info."

**Comment by jaswilli** [comment]
Done. Screenshot for reference:
![screen shot 2017-02-22 at 3 01 47 pm](https://cloud.githubusercontent.com/assets/214142/23232188/f650982a-f90f-11e6-98d5-2fefb87f3c7b.png)
