### ISSUE TITLE
Add Globus account primary username to banner

### ISSUE THREAD

**Issue by tuecke** [globusonline/google-drive-registration-app#9]
The banner has just "Logout" in the upper right corner of the page.  We should also display the primary identity username, and the set of linked identities, like the Globus Auth pages do. That way I can tell at a glance what account I'm logged into.

**Comment by corpulentcoffee** [comment]
Do you want the primary identity username displayed here even if the user's primary identity is not eligible to interact with the GCS server?

**Comment by tuecke** [comment]
Yes.  Like Globus Auth, I think it should show:

Primary identity:
...
Linked identities:
...
...
Logout

Though I don't think there show be horizontal bars between each of the linked identities.
